[package]
name = "folder_derive"
version = "0.1.0"
authors = ["Justin Cullen <jcullen@alum.mit.edu>"]

[dependencies]
syn = { path = "syn" }
synom = "0.11"
quote = "0.3.15"
case = "0.0.1"

[lib]
proc-macro = true
